lunghezza_lista: lunghezza_lista.o genera_lista.o
	gcc -g lunghezza_lista.o genera_lista.o

lunghezza_lista.o: lunghezza_lista.c tipi.h genera_liste.h
	gcc -g -c lunghezza_lista.c 

genera_lista.o: genera_lista.c tipi.h genera_liste.h
	gcc -g -c genera_lista.c 