list_to_array: list_to_array.o genera_lista.o
	gcc -g list_to_array.o genera_lista.o

list_to_array.o: list_to_array.c tipi.h genera_liste.h
	gcc -g -c list_to_array.c

genera_lista.o: genera_lista.c tipi.h genera_liste.h
	gcc -g -c genera_lista.c