azzera_lista: azzera_lista.o genera_lista.o
	gcc -g azzera_lista.o genera_lista.o

azzera_lista.o: azzera_lista.c genera_liste.h tipi.h
	gcc -g -c azzera_lista.c

genera_lista.o: genera_lista.c genera_liste.h tipi.h
	gcc -g -c genera_lista.c