massimo: massimo.o genera_lista.o
	gcc -g massimo.o genera_lista.o

massimo.o: massimo.c tipi.h genera_liste.h
	gcc -g -c massimo.c

genera_lista.o: genera_lista.c tipi.h genera_liste.h
	gcc -g -c genera_lista.c